TEMPERATURA_EM_KELVIN= float(input())
MASSA_MOLAR_DOS_GASES=float(input())

VELOCIDADE_MEDIA_DO_GAS=(3*8.31*TEMPERATURA_EM_KELVIN/MASSA_MOLAR_DOS_GASES)
VELOCIDADE_MEDIA_DO_GAS=VELOCIDADE_MEDIA_DO_GAS**0.5

print("{:.2f}".format(VELOCIDADE_MEDIA_DO_GAS))

